import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Nav from '@/components/nav/nav';
import { Footer } from '@/components/footer/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter} flex flex-col items-center justify-center h-screen w-screen bg-transparent`}
      >
        <div className="flex flex-col items-center justify-between h-[700px] w-[550px] bg-gray-300 rounded-lg">
          <Nav />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
